version = "0.0.1"

[deps]
AIHelpMe = "01402e1f-dc83-4213-a98b-42887d758baa"
GenieFramework = "a59fdf5c-6bf0-4f5d-949c-a137c9e2f353"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
julia = "1"

[Genie]
instantiated_pwd = "/Users/pere/genie/genieawesome/AIHelpUI"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
